# Welcome
# https://probot.github.io/apps/welcome/

# automated comment when a user creates an issue.
newIssueWelcomeComment: >
  We noticed this is your first issue! please make sure to provide as much
  actionable information as possible, as well as any relevant files.

# automated comment when a user creates a pull request.  
newPRWelcomeComment: >
  We noticed this is your first pull request! Please ensure that all tests are
  passing and CICD has returned successfully.

# automated comment when a user has their pull request merged.  
firstPRMergeComment: >
  We noticed this is your first merged pull request! Welcome to the club!