default_stages: [commit, push]
fail_fast: true
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    -   id: detect-private-key
    -   id: trailing-whitespace
    -   id: check-merge-conflict
    -   id: detect-aws-credentials
-   repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.27.0
    hooks:
    -    id: terraform_fmt
    -    id: terraform_tflint
    -    id: terraform_docs
-   repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v2.2.1
    hooks:
    -    id: commitlint
         stages: [commit-msg]