name: Build and Test

on:
  push:
    branches:
      - '*'

env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_DEFAULT_REGION: us-east-1

jobs:
  format:
    name: Format and Lint Terraform Module
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Format and Validate Terraform Module
      run: |
        terraform init
        terraform validate -json
        terraform fmt -check -recursive

    - name: Validate Terraform Module Provider Logic
      run: |
        curl -L "$(curl -Ls https://api.github.com/repos/terraform-linters/tflint/releases/latest | grep -o -E "https://.+?_linux_amd64.zip")" -o tflint.zip && unzip tflint.zip && rm tflint.zip
        chmod +x tflint && ./tflint *.tf

  test:
    name: Unit Test Terraform Module
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v3
      with:
        go-version: '1.19'
        check-latest: true
        cache: true
        cache-dependency-path: test/go.sum
    - name: Run Tests Against Terraform Module
      run: |
        cd test
        go mod download
        go test -v . -timeout 30m
